### ISSUE TITLE
Admin Dashboard Recent Activities Page - Role column showing code instead of human readable text

### ISSUE THREAD

**Issue by paradoxxjm** [slashroots/harvest-v2#103]
The "Role" column in the Recent Activities shows the code for the user roles rather than a human readable description of the role type.

![admindb_recentactivities_rolecolumn](https://cloud.githubusercontent.com/assets/406181/20587390/33228208-b1db-11e6-84b3-aa21f4450427.png)

**Comment by matjames007** [comment]
I suggest using the `development` environment since the staging still has residue from the old method of storing roles to users.  I don't think this issue still exists.
