### ISSUE TITLE
Text placeholder on the Sign In page should be replaced with text that is relevant to HarvestAPI.

### ISSUE THREAD

**Issue by CamiMonte** [slashroots/harvest-v2#152]
![harvest api- signin heading](https://cloud.githubusercontent.com/assets/20387220/22989385/af832566-f383-11e6-853f-fa8d31b18042.png)

**Comment by paradoxxjm** [comment]
@CamiMonte can you provide some context on what kind of text you had environed be placed in header/sub-header section above.

**Comment by paradoxxjm** [comment]
This is a duplicate of #140.
