### ISSUE TITLE
Documentation UI Overflow

### ISSUE THREAD

**Issue by matjames007** [slashroots/harvest-v2#30]
<img width="1167" alt="screen shot 2016-10-20 at 3 08 11 pm" src="https://cloud.githubusercontent.com/assets/1425164/19576077/47656bbe-96d7-11e6-953c-c0b26e5f8575.png">

The response messages overflow the bounding box.

**Comment by leechristophermurray** [comment]
This is due to the styling that comes with redoc. This would have to be fixed on the style-docs-impl branch.
