### ISSUE TITLE
See the Sign up and Sign in links when I'm logged in

### ISSUE THREAD

**Issue by liannegiselle** [slashroots/harvest-v2#53]
**Scenario**
I am logged in and on the developer dashboard

**Expected Result**
I should see my name with a dropdown when I click on my name with the options "Account Settings" and "Logout"

**Actual Result**
I see the Sign Up and Sign In links
![image](https://cloud.githubusercontent.com/assets/8355153/20273241/81c37068-aa5e-11e6-82b7-10b662ca3d92.png)

**Comment by matjames007** [comment]
The navigation component needs to be triggered/refreshed after a successful authentication.

**Comment by matjames007** [comment]
Is this still an issue?

**Comment by paradoxxjm** [comment]
@matjames007 this is addressed once the user is on one of the dashboards. However if you are on the HarvestAPI homepage or the documentation page (see issue#95) then there is an issue is there.
