### ISSUE TITLE
Sign Up: Multiple usernames to one email address

### ISSUE THREAD

**Issue by leechristophermurray** [slashroots/harvest-v2#58]
**SCENARIO:** 
Signing up with different usernames but the same email address.

**ACTUAL RESULT:**
When "submit" is selected, the button becomes disabled, with no feedback to the user as to why. Then the app proceeds with sending activation link.

**EXPECTED RESULT:**
_FEEDBACK:_ "_This email is already being used. If you've forgotten your username and/or password click 'here'._"

"here" would redirect to an account recovery page to guide the user through the process.

**Comment by matjames007** [comment]
Uniqueness of `username` should also be enforced.

**Comment by paradoxxjm** [comment]
@matjames007 see issue #57
