### ISSUE TITLE
Sign In: Page shown after sign up is successful, lacks function

### ISSUE THREAD

**Issue by leechristophermurray** [slashroots/harvest-v2#66]
**SCENARIO:**
After clicking on the activation link and going to the page, the 

**ACTUAL RESULT:**
the page makes successful activation status known. However, it does not allow the user to sign in on it. The user has to click "sign in" from the nav bar to get signed in.

**EXPECTED RESULT:**
Form follows function: functionality needed.

**Comment by matjames007** [comment]
I haven't been able to reproduce this.  Maybe something has changed since @thinkking?

**Comment by leechristophermurray** [comment]
It does seem something has changed since @matjames007 .
