### ISSUE TITLE
Transition from SendGrid to RADA Mail Server

### ISSUE THREAD

**Issue by paradoxxjm** [slashroots/harvest-v2#99]
Change mail server settings from SendGrid to the RADA

Given that we haven't tested the reliability of the RADA mail server, it may be valuable to incorporate a failsafe/failback to Sendgrid if the RADA mail server doesn't respond within a particular time

**Comment by paradoxxjm** [comment]
@nick22891 was this completed already?

**Comment by nickwxo** [comment]
@paradoxxjm Yes this was done
